### ISSUE TITLE
サブ垢から練習用の送信

### ISSUE THREAD

**Issue by akitani3** [akiya3/tieroll#1]
marchandiseに属しているアイテムを削除するとき、子を先に削除すると親子関係にあるためエラーとなるのを直すこと

月曜日にやる

**Comment by akiya3** [comment]
月曜日にやる

**Comment by akiya3** [comment]
やってるけど終わらない

**Comment by akiya3** [comment]
あと一息！

**Comment by akiya3** [comment]
あとupdate後とdestroy後のリダイレクト処理だけ

**Comment by akiya3** [comment]
まだ終わってなかった

**Comment by akiya3** [comment]
まだ終わってなかった（２回目）
hat_controllerのEdit, Update, Destroyロジックを残りのアイテム分である１８個作る
切り出せるところは切り出す。
そのあとリファクタリングして次こそ完了
